### ISSUE TITLE
Any ideas for updating targetSdk?

### ISSUE THREAD

**Issue by Aditya94A** [diegoperini/ffmpeg-android-java#1]
Hey there! Excellent work on this fork! This library is in desperate need of help :)

Do you have any ideas if there's a workaround for getting our targetSdk up? As far as I know, from months of googling, there are none unless we're willing to accept a ridiculous performance slow down (using `--disable-asm` if I remember correctly). 

And that text relocation debacle between Google and FFmpeg does not look like it's going anywhere. We're on our own :(

Any ideas?

**Comment by diegoperini** [comment]
Hi @AdityaAnand1 ,

I haven't tried messing with build files yet. What is your use case that requires such update? 

I believe there is a fork [doing that](https://github.com/kesha-antonov/ffmpeg-android-java). If you can check this fork for me, I can maybe later incorporate changes if appropriate.

**Comment by Aditya94A** [comment]
The problem is:

- Starting with 6.0, you now have to ask for permissions at runtime
- If your targetSdk <= 22, Android assumes that you don't yet support runtime permissions
- This is FFmpeg, I'm working with files and I'm outputting files, so I need write external storage permission to write to the SD card
- But since my targetSdk = 22, users must grant my permissions at install time (so my app can write to the SD card below marshmallow)
- Again, starting with marshmallow, that doesn't matter, you still have to ask for permissions at runtime 
- This I can't do since my targetSdk is stuck at 22. (why? because of the text relocation thing, if I raise my targetSdk, FFmpeg will simply not work anymore)

So my simple use case is making FFmpeg output to the SD card on Android 6.0+. 

I have literally received over a hundred 1 stars just because my app can't write to external storage on 6.0+, so this is insanely high priority for me, but after months of tinkering I still haven't gotten it to work. And this is a rather delicate issue, since once I raise my targetSdk in production I can't ever go back down so I need to tread super carefully.

Yes, I came across that fork too, but it seems to be stuck at 22 as well.

**Comment by diegoperini** [comment]
Can you try `compile 'com.github.diegoperini:ffmpeg-android-java:v0.4.8'` and tell me the results @AdityaAnand1 ?

**Comment by Aditya94A** [comment]
Arggh, I tried switching out the dependencies in my project and proguard spit out a few errors after not finding `FFmpegObserver` (P.S: Perhaps you might want to look into this?) and since I use proguard even in debug builds (otherwise I'd have to multi dex) it didn't work with my existing project even after I tried using `keep` for some weird reason.

\</rant>

Anyways, I'll try again in a fresh project (maybe just build the sample app?) and report back with something useful soon :)

**Comment by diegoperini** [comment]
Could you paste the exact error/stacktrace just for reference purposes?

**Comment by Aditya94A** [comment]
Sorry! I took a month's sabbatical from android development lol.

Now I'm back and still facing the same problem. Nevermind the proguard issue, I'm positive it was some error in my configuration. But this library not being able to write to the SD card is, as far as my testing has shown, a much more significant issue.

It's easily reproducible too. For example, running the following command (even with your updated fork) gives a "permission denied" error (same as with the original repo)

It's just a simple command to cut an audio file (from 5 to 10 seconds from input.mp3 and save it to output.mp3)

```
"-ss", "5000", "-i", "/storage/input.mp3", "-t", "5000", "-acodec", "copy", "/storage/output.mp3"
```

The complete output it gives:

```
 Input #0, mp3, from '/storage/input.mp3':
 Metadata:
 major_brand     : mp42
 minor_version   : 0
 compatible_brands: isomavc1mp42
 creation_time   : 2009-08-09 10:36:42
 encoder         : Lavf52.110.0
 Duration: 00:03:13.15, start: 0.000000, bitrate: 128 kb/s
 Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 128 kb/s
 /storage/output.mp3: Permission denied
```

So, given that it is able to get the metadata for the input, we know that it can read from the SD card, but something goes wrong when it tries to write the output to the SD card.

The above command works just fine when the output points to a location in the internal storage. I've tested the above on a physical device running marshmallow and I can confirm that going into permissions, the app DOES indeed have write to external storage permission, but for some reason, FFmpeg can't seem to see that.

Any ideas?

**Comment by diegoperini** [comment]
Very interesting indeed. I'm trying to reproduce the issue with my code but for some reason everything seems normal. To be able to make sure it's really an issue of ffmpeg, can you use the following helper method to replace `"/storage/output.mp3"` in your command with the result returned from the function `getOutputMediaFile()`.

Below is the sample code I need you to try (in Kotlin).

```Kotlin
fun getOutputMediaFile(type: MediaType, suffix: String = “”, obfuscate: Boolean = false): String {
            // To be safe, you should check that the SDCard is mounted
            // using Environment.getExternalStorageState() before doing this.

            val mediaStorageDir = File(Environment.getExternalStoragePublicDirectory(
                    Environment.DIRECTORY_PICTURES), “myApp”)

            // This location works best if you want the created images to be shared
            // between applications and persist after your app has been uninstalled.

            // Create the storage directory if it does not exist
            if (!mediaStorageDir.exists()) {
                if (!mediaStorageDir.mkdirs()) {
                    Log.e(“Error”, “failed to create directory”)
                    return null!! // crash
                }
            }

            // Create a media file name
            val timeStamp = SimpleDateFormat(“yyyyMMdd_HHmmss”).format(Date())
            val mediaFile: File
            if (type === MediaType.IMAGE) {
                mediaFile = File(mediaStorageDir.path + File.separator +
                        “IMG_” + timeStamp + suffix + “.jpg” + if (obfuscate) “_” else “”)
            } else if (type === MediaType.VIDEO) {
                mediaFile = File(mediaStorageDir.path + File.separator +
                        “VID_” + timeStamp + suffix + “.mp4” + if (obfuscate) “_” else “”)
            } else {
                Log.e(“Error”, “Unsupported media type”)
                return null!! // crash
            }

            return mediaFile.path
        }

enum class MediaType {
    IMAGE, VIDEO, AUDIO;

    override fun toString(): String {
        return when (this) {
            IMAGE -> “image”
            VIDEO -> “video”
            AUDIO -> “audio”
        }
    }

    companion object {
        fun fromString(s: String): MediaType? {
            if (IMAGE.toString() == s)
                return IMAGE
            else if (VIDEO.toString() == s)
                return VIDEO
            else if (AUDIO.toString() == s)
                return AUDIO
            else
                return null
        }
    }
}
```

Edit: @mithataydogmus take a look at this.

**Comment by Aditya94A** [comment]
I'll try it out. And I'll try to create a minimal example that isolates the problem I'm having.

**Comment by Aditya94A** [comment]
So I made a [test repo](https://github.com/AdityaAnand1/FFmpeg-test), it copies a test file from the assets folder to the external storage (this can also be used to test write permission), then it runs an ffmpeg command to copy the input file to a user specified output location. It has 26 targetSdk (>22!!)

* It works jut fine when I pick the output location to somewhere within the device's internal storage.
* I get the same permission denied error, when I pick a location on the external SD card.

I tested it on my galaxy note 4, arm v7, android 6.0.0 ([Here](https://github.com/AdityaAnand1/FFmpeg-test/raw/master/app/test.apk)'s the link to download the debug apk)

The way the internal and external storages work is rather [weird](https://developer.android.com/training/basics/data-storage/files.html). Even when there's no external sd card, we're still guaranteed to have two places to save our files to, the internal storage (which means an app's private files) and the external storage (user accessible stuff). So on top of this, if a user adds an SD card, then it's another (third) place to store files. The first one (files only available to the app) doesn't really matter for our use case.

**Comment by diegoperini** [comment]
In your "Helper.java", there is a line like this.

```Java
public static final String INPUT_PATH = Environment.getExternalStorageDirectory() + "/" + "input.mp3";
```

Can you change `Environment.getExternalStorageDirectory()` prefix with `Environment.getExternalStoragePublicDirectory()`? If that doesn't work, you should also try `Context.getExternalFilesDir()` to check whether it is a fs level permission error or app level one.

We should also collect some verbose info. Can you log `Environment.getExternalStorageState()` to see if it is writable?

For some reason it works when I create the file with the code below:
```Java
new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES), “myApp”)
```

Appendix:
[getExternalFilesDir](https://developer.android.com/reference/android/content/Context.html#getExternalFilesDir(java.lang.String))
[getExternalStoragePublicDirectory](https://developer.android.com/reference/android/os/Environment.html#getExternalStoragePublicDirectory(java.lang.String))

**Comment by diegoperini** [comment]
@AdityaAnand1 can you also try this repo if it works?

https://github.com/inFullMobile/videokit-ffmpeg-android

**Comment by diegoperini** [comment]
@AdityaAnand1 you might want to check out this:

https://github.com/bravobit/FFmpeg-Android

**Comment by Aditya94A** [comment]
Thanks @diegoperini I'm just testing it out..

Seems to work on Android v5.0 - v7.0 genymotion emulators, my lollipop physical device as well as on an API 22 x86 default android studio emulator.

I'm reworking my entire application right now and hope to resolve this soon. I think that my earlier SD card writing issue was unrelated to the x86 support issue (which seems to be fixed in bravobit's repo) which was unrelated to the targetedSdk issue. I'm not sure whether this targetSdk thing is resolved, I'm going to test that right now.
