### ISSUE TITLE
Question about ContextProvider

### ISSUE THREAD

**Issue by vxhviet** [diegoperini/ffmpeg-android-java#4]
Hi @diegoperini ,

As you could have known the memory leak issue with the original WritingMind's solution is because of storing it directly in a field within the FFmpeg singleton.

I have the chance to look at both your [`FFmpegContextProvider`](https://github.com/diegoperini/ffmpeg-android-java/blob/master/FFmpegAndroid/src/main/java/com/github/hiteshsondhi88/libffmpeg/FFmpegContextProvider.java) as well as Bravobit's [`FFbinaryContextProvider`](https://github.com/bravobit/FFmpeg-Android/blob/46616dd60f41a0f899a1508100984f8dea240f8f/android-ffmpeg/src/main/java/nl/bravobit/ffmpeg/FFmpeg.java#L33). Both solutions utilize the use of an anonymous class that implement an interface that would provide the Activity's context on demand. Is it just by hiding the `Context` under an interface like this would allow the garbage collector to collect it whenever the activity get killed? Is there any resource that I can read more on this matter?

Thank you so much for your time.

**Comment by vxhviet** [comment]
And while we are at it, if the aim is to prevent memory leaks, doesn't `WeakReference` already solve this issue? Why do we need to go the extra code route with that interface?

**Comment by diegoperini** [comment]
@vxhviet Firstly, yes `WeakReference` perfectly solves the problem. The logic behind the provider approach doesn't actually fix the leak if the anonymous interface instance captures the context by reference. So why the hassle? The thing is, many users of the library directly use these methods inside their activities or fragments. When you call your fragment's `getActivity()` inside the anonymous instance's `provide()` method, you are not actually capturing the context, but only a reference to the fragment instance which is safer. As for the Activity approach, if you capture the your activity's `this` via something like `final Activity self = this;` and use `self` inside `provide()`, it becomes a circular dependency which can be handled by garbage collector safely.
