### ISSUE TITLE
how to generate video from bitmap array.

### ISSUE THREAD

**Issue by janeSmith99221** [diegoperini/ffmpeg-android-java#5]
I'm trying to generate video from multiple images using ffmpeg it's works because I'm passing images prefix%003.extension form from local storage path. but I want to reduce this local storage step and pass bitmap array to video generation directly.

**Comment by diegoperini** [comment]
This is an old, unmaintained fork @janeSmith99221 , please see: https://github.com/WritingMinds/ffmpeg-android-java

**Comment by janeSmith99221** [comment]
done with sequence encoder.
